### ISSUE TITLE
Extend Session Duration - Expired Token

### ISSUE THREAD

**Issue by antoineaws** [aws-samples/amazon-kendra-langchain-extensions#11]
Team,
Looking for a way to extend the session duration. Currently, after a few minutes, we start getting expired token and would need to stop the `streamlit run app.py` and run it again.

Any thoughts / suggestions?
Thanks.

**Comment by aastha78** [comment]
i'm getting same issue, can anyone help

**Comment by aastha78** [comment]
Hii, the issue was resolved by changing the security group permission for the port of the underlying EC2 instance.

**Comment by MithilShah** [comment]
The streamlit app is meant for demo purpose only. There are alternatives to the expired token problem, but outside the scope of this repo.
