### ISSUE TITLE
Curtailed responses from Flan XL and XXL SageMaker endpoints

### ISSUE THREAD

**Issue by mrwadams** [aws-samples/amazon-kendra-langchain-extensions#13]
Hi,

I've noticed when using SageMaker endpoints that the responses returned from the LLMs (Flan XL and XXL) are very short compared to what is returned when using OpenAI.

I initially thought this just might be down to the capability of the open source models so adapted the script to work with Falcon-40B deployed on SageMaker. Again, when running the script I get very short responses back that look like they've been cut off mid-sentence. See the screenshot below for an example of the typical length of response that's generated.
![image](https://github.com/aws-samples/amazon-kendra-langchain-extensions/assets/2872334/f709ac54-b603-4340-b4cc-c0227f95258e)

Checking my CloudWatch logs I can see that there's a max_new_tokens parameter being passed to the model which I suspect is what's limiting the output, but it doesn't seem possible to change the value of that parameter from the default of 20.

Is it possible to adjust that parameter to allow the models to return more output in response to each question?

Thanks.

**Comment by mikereinhold** [comment]
The max_length parameter in model_kwargs controls the max response. For example:

https://github.com/aws-samples/amazon-kendra-langchain-extensions/blob/28cb1d4de7cf3bfe8984c6365ce248c12e8b77e0/samples/kendra_chat_flan_xl.py#L45

if you want to allow longer responses & avoid cutoff, increase the max_length value.

**Comment by MithilShah** [comment]
Closing because inactive
