### ISSUE TITLE
PydanticUserError

### ISSUE THREAD

**Issue by aastha78** [aws-samples/amazon-kendra-langchain-extensions#23]
PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`. For further information visit https://errors.pydantic.dev/2.0.2/u/root-validator-pre-skip

can anyone help with this error

**Comment by ApoorvRChincholkar** [comment]
I was able to resolve this by running 

`pip install pydantic==1.8`

**Comment by MithilShah** [comment]
@aastha78 is this working for you now?

**Comment by MithilShah** [comment]
Closing because inactive.
