### ISSUE TITLE
[Feature request] Amazon Bedrock support

### ISSUE THREAD

**Issue by athewsey** [aws-samples/amazon-kendra-langchain-extensions#31]
Hi team & thanks for the sample,

I see kendra_retriever_samples is currently supporting OpenAI, Anthropic by direct API key, and a few SageMaker models: But it would be great if we could provide Amazon Bedrock support also?

**Comment by KamilLegault** [comment]
Especially given that LangChain already supports it....

**Comment by zhenghongpeng** [comment]
If you can get AWS support on Bedrock on your AWS account, we have implemented Bedrock claude at the backend.

**Comment by madtank** [comment]
> If you can get AWS support on Bedrock on your AWS account, we have implemented Bedrock claude at the backend.

I have bedrock enabled, can you explain how to use claude with bedrock with this solution? I see option for claude env api key, how do I use with boto3 instead?

**Comment by MithilShah** [comment]
Added Titan and Claudev2 support

**Comment by madtank** [comment]
Thanks for adding this, confirmed it works great with Claude V2.
