### ISSUE TITLE
response from Llama2 and Falcon40B are truncated

### ISSUE THREAD

**Issue by yogishpa** [aws-samples/amazon-kendra-langchain-extensions#37]
When tried with Llama2 and Falcon40B are truncated for all questions. Tried several different hyperparameters like 

[model_kwargs={"max_new_tokens":1024,"max_length":512,"top_k": 50, "top_p": 0.95,"temperature":0.6,"repetition_penalty":1.2},

but this doesn't seem to be getting fixed. Please check.

**Comment by MithilShah** [comment]
Fixed with the latest release
