### ISSUE TITLE
 Unable to locate credentials

### ISSUE THREAD

**Issue by muntherqasaimeh** [aws-samples/amazon-kendra-langchain-extensions#4]
Hello.
after the local server run I tried to enter an input to the search box and press enter to get results from Kendra then I found Unable to locate credentials error occurred
why this error occurred and how to solve it?
screenshot Attached
![image](https://github.com/aws-samples/amazon-kendra-langchain-extensions/assets/80498650/a6c7253f-45e3-4471-aeea-43dcae239d71)

**Comment by dimwael** [comment]
Have you found a solution ?

**Comment by dimwael** [comment]
You need to grant policy with ec2:
   "Action": "ec2:DescribeTags"
You may also need to grant permissions for Kendra and SageMaker endpoint as well. 
I hope that helps

**Comment by ApoorvRChincholkar** [comment]
Have you installed aws cli and set up the credentials locally using aws configure?

**Comment by MithilShah** [comment]
@muntherqasaimeh are you still facing issues? Will close the ticket if now.
