### ISSUE TITLE
Is the prompt format for llama-2 correct?

### ISSUE THREAD

**Issue by utility-aagrawal** [aws-samples/amazon-kendra-langchain-extensions#60]
Hi,

Thank you for sharing your work here! It's very helpful. I am working on a RAG pipeline using Kendra, langchain and llama-2. I created a Kendra index and have been using llama-2 python script for Q&A. I see the prompts in the py file but they don't seem to be following the correct llama-2 format. Is that handled somewhere else in the code. I couldn't find where it is. Can you point me to it?

As per my understanding, this is the correct format to prompt Llama-2: https://huggingface.co/blog/llama2#how-to-prompt-llama-2

Let me know in case of any questions. Thanks!

**Comment by MithilShah** [comment]
I havent seen a need for special prompt. Tested with the one that we have [here](https://github.com/aws-samples/amazon-kendra-langchain-extensions/blob/main/kendra_retriever_samples/kendra_chat_llama_2.py) and it seems to work well. Are you seeing any issues?

**Comment by MithilShah** [comment]
Fixed
