### ISSUE TITLE
Querry through specific data source

### ISSUE THREAD

**Issue by ajitDignizant** [aws-samples/amazon-kendra-langchain-extensions#65]
i have added 3 to 4 s3 buckets as data sources in one kendra index, but while retriving the data from AmazonKendraRetriever(indexId,region) it checks all the datasources  and give the results but i want to check only specific s3 data sources. How to configure these in code .

**Comment by MithilShah** [comment]
You can make the data source id Facetable in Kendra, and then use a filter while issuing the query using the data sources from which you would like to get the response.

**Comment by ajitDignizant** [comment]
okay great ,in enterprise edition AWS provides  50 data sources to add into one kendra index . But if the the data is very huge and we connect one  data source with one s3 bucket  and inside this  different folder structures are available for storing the large amount of  files. In this case how to serach specific s3 folder structure files by usnig AmazonKendraRetriever(indexId,region,credentials) through code .

**Comment by MithilShah** [comment]
I think its best to reach out to AWS support for this or try out https://repost.aws/
