### ISSUE TITLE
Issue running with LangChain later version.

### ISSUE THREAD

**Issue by nareshnagpal06** [aws-samples/amazon-kendra-langchain-extensions#9]
I was getting below error when I used latest version of langchain (0.0.178.0). 

**kendra_chat_flan_xl.py", line 42, in build_chain
    llm=SagemakerEndpoint(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SagemakerEndpoint
content_handler
  instance of LLMContentHandler expected (type=type_error.arbitrary_type; expected_arbitrary_type=LLMContentHandler)**

After rolling back to langchain 0.0.137.0, it started working. Is this expected?

**Comment by MithilShah** [comment]
Updated to latest version of langchain
